version: '3.3'

services:
  app:
    container_name: app
    build: .
    depends_on:
      - mssql
    ports:
      - 3000:3000
    environment:
      - DB_HOST=mssql
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=MyStr0ng@password
      - DB_NAME=BUDG
  mssql:
    # image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: mssql
    build: ./db
    ports:
      - 1433:1433
    volumes:
      - ./mssql-data:/var/opt/mssql
